disabled_rules:
  - trailing_comma
  - identifier_name
  # Formatting rules — swift-format is authoritative for these
  - opening_brace
  - closing_brace
  - closure_spacing
  - colon
  - comma
  - leading_whitespace
  - return_arrow_whitespace
  - statement_position
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - vertical_whitespace

opt_in_rules:
  - empty_count

line_length:
  warning: 120
  error: 150

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 60
  error: 100

excluded:
  - .build
  - Package.swift
