name: Lint GitHub Actions

on:
  pull_request:
    branches:
      - main

    paths:
      - '.github/workflows/*.yml'

  push:
    branches:
      - main

    paths:
      - '.github/workflows/*.yml'

permissions:
  contents: read

jobs:
  shellcheck:
    name: Run actionlint

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run actionlint
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "::add-matcher::.github/matchers/actionlint.json"

          gh extension install cschleiden/gh-actionlint
          gh actionlint -color
        shell: bash
